services:
    import.importer.lambweston_syncforce:
        class: Endroid\Import\Importer\Importer
        arguments:
            - [
                  '@import.loader.language',
                  '@import.loader.product_website_collection',
                  '@import.loader.product_category_info_collection',
                  '@import.loader.product',
                  '@import.loader.menu'
              ]
        tags:
            - { name: endroid.import.importer, alias: lambweston-syncforce }
    import.loader.language:
        class: SyncForceImportBundle\Loader\LanguageLoader
    import.loader.product_website_collection:
        class: SyncForceImportBundle\Loader\ProductWebsiteCollectionLoader
        arguments: [ '@import.client.syncforce' ]
    import.loader.product_category_info_collection:
        class: SyncForceImportBundle\Loader\ProductCategoryInfoCollectionLoader
        arguments: [ '@import.client.syncforce' ]
    import.loader.product:
        class: SyncForceImportBundle\Loader\ProductLoader
        arguments: [ '@import.client.syncforce' ]
    import.loader.menu:
        class: SyncForceImportBundle\Loader\MenuLoader
        arguments: [ '@import.client.syncforce' ]
    import.client.syncforce:
        class: SyncForceImportBundle\Client\SyncForceClient