services:
    menu.menu_admin:
        class: MenuBundle\Admin\MenuAdmin
        arguments: [null,  MenuBundle\Entity\MenuItem, AdminBundle:BaseAdmin]
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Navigation, label: Menus, label_catalogue: messages }

    menu.twig_extension:
        class: MenuBundle\Twig\Extension\MenuExtension
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: twig.extension }

    menu.builder:
        class: MenuBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]
        calls:
            - [ 'setContainer', [ '@service_container' ] ]

    menu.main:
        class: Knp\Menu\MenuItem
        factory: [ '@menu.builder', 'createMenuMain' ]
        arguments: [ '@request_stack' ]
        tags:
            - { name: knp_menu.menu, alias: menu_main }

    menu.footer:
        class: Knp\Menu\MenuItem
        factory: ['@menu.builder', 'createMenuFooter']
        arguments: [ '@request_stack' ]
        tags:
            - { name: knp_menu.menu, alias: menu_footer }
