framework:
    assets:
        packages:
            admin:
                json_manifest_path: "%kernel.project_dir%/public/build/admin/manifest.json"
            app:
                json_manifest_path: "%kernel.project_dir%/public/build/app/manifest.json"
