easy_admin:
    site_name: Symfony Application
    design:
        brand_color: '#222f5b'
    entities:
        User:
            label: User
            class: App\Entity\User
            form:
                fields:
                    - { property: 'roles', type: 'choice', type_options: { expanded: true, multiple: true, choices: { 'Normal user': 'ROLE_USER', 'Administrator': 'ROLE_ADMIN' }}}
            list:
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'roles', label: 'Roles' }
            new:
                fields:
                    - { property: 'email', label: 'Email' }
                    - { property: 'plainPassword', label: 'Password', type: 'password' }
                    - { property: 'roles', label: 'Roles' }
            edit:
                fields:
                    - { property: 'email', label: 'Email' }
                    - { property: 'plainPassword', label: 'Password', type: 'password' }
                    - { property: 'roles', label: 'Roles' }
