endroid_finance:
    categories:
        -
            name: Groceries / food
            terms:
                - 'mitra'
                - 'jumbo'
                - 'albert heijn'
                - 'bakkerij'
                - 'kwalitaria'
                - 'panos'
                - 'de toren'
                - 'coop supermarkt'
                - 'slijter'
                - 'kruidvat'
        -
            name: Netvlies
            terms:
                - 'netvlies'
        -
            name: Recurring costs
            terms:
                - 'tele2'
                - 'transip'
                - 'chipkaart'
                - 'oranjepakket'
                - 'betaalpakket'
                - 'kapper'
                - 'parkeer'
        -
            name: Fixed income / expenses
            terms:
                - 'aegon'
                - 'belastingdienst'
                - 'jajw'
                - 'van bielder'
                - 'debetrente'
        -
            name: Events / theater
            terms:
                - 'chasse'
