framework:
  messenger:
    default_bus: messenger.bus.commands
    buses:
      messenger.bus.commands:
        middleware:
          - validation
          - doctrine_transaction
      messenger.bus.queries:
        middleware:
          - validation
      messenger.bus.events:
        default_middleware: allow_no_handlers
        middleware:
          - validation
