nelmio_security:
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY
        content_types: []

    external_redirects:
        # Prevent unwanted redirects and redirect to dashboard
        override: 'sonata_admin_dashboard'

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'

    csp:
        # See https://github.com/nelmio/NelmioSecurityBundle#content-security-policy
        enabled: true
        hosts: []
        content_types: []
        report_logger_service: monolog.logger.security
        enforce:
            # For older browsers
            level1_fallback: true
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            # Adapt directives to browser
            browser_adaptive:
                enabled: true
            # Block mixed HTTP/HTTPS content
            block-all-mixed-content: true
