hwi_oauth:
    firewall_names: [main]
    resource_owners:
        google:
            type: google
            client_id: '%env(GOOGLE_OAUTH_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_OAUTH_CLIENT_SECRET)%'
            scope: "email profile"
        github:
            type: github
            client_id: '%env(GITHUB_OAUTH_CLIENT_ID)%'
            client_secret: '%env(GITHUB_OAUTH_CLIENT_SECRET)%'
            scope: 'user:email,public_repo'
