nelmio_api_doc:
    routes:
        path_patterns:
            - ^/api/
    documentation:
        info:
            title: API
            description: Documentation
            version: 1.0.0
        securityDefinitions:
            api_key:
                type: apiKey
                description: Your Json Web Token
                name:  authorization
                in: header
        security:
            api_key: []
