twig:
    paths:
        templates: ~
        templates/bundles/FOSUser: FOSUser
        templates/bundles/EndroidGuide: EndroidGuide
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - bootstrap_3_layout.html.twig
