language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1

addons:
  mariadb: '10.3'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install

script:
  - sh check.sh
