language: php

php:
  - 7.1

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --no-interaction

script:
  - cp .env.travis .env
  - vendor/bin/phpunit

notifications:
  email: info@endroid.nl
