sudo: required
services:
  - docker

branches:
  only:
    tags:
      - /^[0-9\.]+$/

env:
  - DOCKER_COMPOSE_VERSION=1.14.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cp .env.test .env

before_script:
  - sudo /etc/init.d/mysql stop # Make sure port 3306 is not already occupied

script:
  - sudo chmod 777 -R .
  - docker-compose build >/dev/null
  - docker-compose up -d >/dev/null
  - sleep 10 # MariaDB takes some time to initialize
  - docker-compose exec --user 1000 php /bin/sh reset.sh
  - docker-compose exec --user 1000 php /bin/sh check.sh
