language: php

services:
  - mariadb
  - elasticsearch

php:
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - echo $COMPOSER_BIN_DIR
  - composer self-update

script:
  - bin/build

notifications:
  email: info@endroid.nl
