language: php

services:
  - elasticsearch

addons:
  mariadb: 10.3

php:
  - 7.2

before_install:
  - phpenv config-add travis.php.ini
  - composer self-update

script:
  - cp development/.env.travis development/.env
  - bin/build
  - cd symfony-start
  - bin/setup test
  - bin/console server:run 0.0.0.0:9090 -q &
  - bin/test

notifications:
  email: info@endroid.nl
