#!/usr/bin/env bash

set -e # Break on any error

rm -rf symfony-start

# Always start from website skeleton
composer create-project symfony/website-skeleton symfony-start -s beta --no-install

vendor/bin/teleport development symfony-start $@

(
    cd symfony-start/vendor
    ln -s ../../vendor/endroid endroid
)

(
    cd symfony-start
    bin/create
    bin/setup
    bin/test
)
