#!/usr/bin/env bash

# Always operate from script directory
cd "$(dirname "$0")"

set -e # Break on any error

# Further build application
(
    cd application

    # Fix for pending recipes
    sed -i '/Import\\Bundle/d' config/bundles.php

    composer install

    ../overwrite

    rm -rf features/demo.feature

    # Set up frontend
    (
        cd frontend
        ./rebuild
    )
)

# Reset the application itself to make it functional
(
    cd application
    ./reset
)
