#!/usr/bin/env bash

if [ ! -f development/.env.local ]; then
    echo "Please create a .env.local file for production before deploying"
    exit 1
fi

./stop
echo y | docker-compose rm

git reset --hard
git pull
sed -i -e 's/localhost/endroid.nl/g' docker/nginx/nginx.conf

docker-compose build
docker-compose up -d

docker-compose exec mariadb mysql -proot -Bse "DROP DATABASE application"
docker-compose exec nginx docker/nginx/ssl/certbot
docker-compose exec --user 1000 php /bin/sh bin/build play
docker-compose exec --user 1000 php /bin/bash -c "cd symfony-start && bin/setup prod"
docker-compose exec --user 1000 php /bin/bash -c "cd symfony-start && bin/console doctrine:fixtures:load -n"
