#!/usr/bin/env bash

if [ ! -f development/.env.local ]; then
    echo "Please create a .env.local file for production with APP_ENV=prod before deploying"
    exit 1
fi

docker-compose stop
echo y | docker-compose rm

git reset --hard
git pull
sed -i -e 's/localhost/endroid.nl/g' docker/nginx/nginx.conf

docker-compose build
docker-compose up -d

docker-compose exec mysql mysql -proot -Bse "DROP DATABASE IF EXISTS application"
docker-compose exec nginx docker/nginx/ssl/certbot
docker-compose exec --user 1000 php-cli /bin/bash bin/build prod
docker-compose exec --user 1000 php-cli /bin/bash -c "cd symfony-start && bin/setup"
docker-compose exec --user 1000 php-cli /bin/bash -c "cd symfony-start && bin/console doctrine:fixtures:load -n"
