version: '3'
services:
    elasticsearch:
        ports:
            - 9200:9200
    kibana:
        ports:
            - 5601:5601
    mailhog:
        ports:
            - 8025:8025
    mariadb:
        ports:
            - 3306:3306
    php:
        environment:
            - ENVIRONMENT=dev
            - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
            - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
            - GITHUB_OAUTH_TOKEN=${GITHUB_OAUTH_TOKEN}
        ports:
            - 9090:9090
    redis:
        ports:
            - 6379:6379
