version: '3'
services:
    elasticsearch:
        image: elasticsearch:5
        expose:
            - 9200
    kibana:
        image: kibana:5
        expose:
            - 5601
    mailhog:
        image: mailhog/mailhog
        expose:
            - 1025
            - 8025
    mariadb:
        build: docker/mariadb/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: application
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
        expose:
            - 3306
    redis:
        image: redis:3
        expose:
            - 6379
    php:
        build: docker/php/
        environment:
            - ENVIRONMENT=prod
            - GITHUB_OAUTH_TOKEN=${GITHUB_OAUTH_TOKEN}
        volumes:
            - .:/var/www/html
            - ~/.gitconfig:/var/www/.gitconfig
            - ~/.gitignore_global:/var/www/.gitignore_global
            - ~/.ssh:/var/www/.ssh
            - ~/.cache/yarn:/var/www/.cache/yarn
            - ~/.composer/cache:/var/www/.composer/cache
        depends_on:
            - elasticsearch
            - mariadb
            - redis
        dns:
            - 8.8.8.8
            - 8.8.4.4
        expose:
            - 9000
    nginx:
        build: docker/nginx/
        volumes:
            - .:/var/www/html
            - ~/.letsencrypt:/etc/letsencrypt
        depends_on:
            - php
        environment:
            - DOMAIN=${DOMAIN}
        ports:
            - 80:80
            - 443:443
            - 8000:8000
