version: '3'
services:
    elasticsearch:
        ports:
            - 9200:9200
    kibana:
        ports:
            - 5601:5601
    mongodb:
        ports:
            - 27017:27017
    mariadb:
        ports:
            - 3306:3306
    rabbitmq:
        ports:
            - 15672:15672
    redis:
        ports:
            - 6379:6379
    php:
        ports:
            - 8080:8080