version: '3'
services:
    elasticsearch:
        image: elasticsearch:5
        expose:
            - 9200
    kibana:
        image: kibana:5
        expose:
            - 5601
    mailhog:
        image: mailhog/mailhog
        command: -api-bind-addr 0.0.0.0:10025 -ui-bind-addr 0.0.0.0:10025 -smtp-bind-addr 0.0.0.0:3025
        expose:
            - 3025
            - 10025
    mariadb:
        build: docker/mariadb/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: application
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
        expose:
            - 3306
#    prediction_io:
#        build: docker/prediction-io
#        tty: true
#        volumes:
#          - ./docker/prediction-io:/docker
#        ports:
#            - 7070:7070
#            - 8000:8000
    redis:
        image: redis:3
        expose:
            - 6379
    selenium_hub:
        image: selenium/hub:3
        expose:
            - 4444
    selenium_node_chrome:
        image: selenium/node-chrome:3
        depends_on:
            - selenium_hub
        environment:
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        expose:
            - 5555
    php:
        build: docker/php/
        environment:
            - ENVIRONMENT=prod
        volumes:
            - .:/var/www/html
            - ~/.gitconfig:/var/www/.gitconfig
            - ~/.gitignore_global:/var/www/.gitignore_global
            - ~/.ssh:/var/www/.ssh
            - ~/.cache/yarn:/var/www/.cache/yarn
#            - ~/.composer/cache:/var/www/.composer/cache
        depends_on:
            - elasticsearch
            - mariadb
#            - prediction_io
            - redis
            - selenium_hub
        dns:
            - 8.8.8.8
            - 8.8.4.4
        expose:
            - 9000
    nginx:
        build: docker/nginx/
        volumes:
            - .:/var/www/html
            - ~/.letsencrypt:/etc/letsencrypt
        depends_on:
            - php
        environment:
            - DOMAIN=${DOMAIN}
        ports:
            - 80:80
            - 443:443
