version: '3'
services:
#    elasticsearch:
#        ports:
#            - 9200:9200
#    kibana:
#        ports:
#            - 5601:5601
    mailcatcher:
        ports:
            - 1080:1080
#    mongodb:
#        ports:
#            - 27017:27017
    mariadb:
        ports:
            - 3306:3306
#    rabbitmq:
#        ports:
#            - 15672:15672
#    redis:
#        ports:
#            - 6379:6379
    php:
        environment:
            - ENVIRONMENT=dev
            - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
            - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
            - GITHUB_OAUTH_TOKEN=${GITHUB_OAUTH_TOKEN}
        ports:
            - 8080:8080
