version: '3'
services:
    mailhog:
        image: mailhog/mailhog
        expose:
            - 1025
            - 8025
    mysql:
        build: docker/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: application
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        expose:
            - 3306
    redis:
        image: redis:5
        expose:
            - 6379
    mercure:
        image: dunglas/mercure
        environment:
            JWT_KEY: 3f32b715f03fababaf4c843af4bf3ae1
            CORS_ALLOWED_ORIGINS: '*'
            ALLOW_ANONYMOUS: 1
        ports:
            - 3000:80
    php:
        build: docker/php/
        environment:
            - ENVIRONMENT=prod
            - GITHUB_OAUTH_TOKEN=${GITHUB_OAUTH_TOKEN}
        volumes:
            - .:/var/www/html
            - ~/.gitconfig:/var/www/.gitconfig
            - ~/.gitignore_global:/var/www/.gitignore_global
            - ~/.ssh:/var/www/.ssh
            - ~/.cache/yarn:/var/www/.cache/yarn
            - ~/.composer/cache:/var/www/.composer/cache
        depends_on:
            - mysql
            - redis
        dns:
            - 8.8.8.8
            - 8.8.4.4
        expose:
            - 9000
    nginx:
        build: docker/nginx/
        volumes:
            - .:/var/www/html
            - ~/.letsencrypt:/etc/letsencrypt
        depends_on:
            - php
        environment:
            - DOMAIN=${DOMAIN}
        ports:
            - 80:80
            - 443:443
            - 8000:8000
