#!/usr/bin/env bash

# Always operate from script directory
cd "$(dirname "$0")"

readonly SYMFONY_VERSION=3.4
readonly SHOW_COMMANDS=false

set -e # Break on any error

if [ $SHOW_COMMANDS = true ]; then
    set -o xtrace
fi

if [ ! -f docker/nginx/nginx.conf ]; then
    cp docker/nginx/nginx.conf.dist docker/nginx/nginx.conf
fi

if [ ! -f .env ]; then
    cp .env.dist .env
fi

if [ ! -f overwrites/.env ]; then
    cp overwrites/.env.dist overwrites/.env
fi

# When not in docker start docker and execute script again
if [ ! -d "/var/www/html/docker" ] ; then
    ./stop
    echo y | docker-compose rm
    docker-compose build
    docker-compose up -d
    docker-compose exec nginx docker/nginx/ssl/certbot
    docker-compose exec --user 1000 php /bin/sh rebuild
    exit 0 # Do not continue as we already ran the script above
fi

rm -rf application

readonly SYMFONY_VERSION_MAJOR=^$SYMFONY_VERSION

# Create new project from skeleton and build parts
composer create-project symfony/skeleton:$SYMFONY_VERSION_MAJOR application -s beta

# Further build application
(
    cd application

    composer config minimum-stability beta

    # Symlink directories
    ln -s ../features features
    ln -s ../frontend frontend
    ln -s ../templates templates
    ln -s ../translations translations

    cp config/services.yaml config/services_default.yaml

    (
        cd vendor
        ln -s ../../vendor/endroid endroid
    )

    # Kernel does not work in symlink path so symlink src directories
    (
        cd src
        for directory in `find ../../src/* -maxdepth 0 -type d`
        do
            rm -rf `basename $directory`
            ln -s $directory `basename $directory`
        done
    )

    # Allow auto configuration for user contributed bundles
    composer config extra.symfony.allow-contrib true

    # Add private repositories
    composer config repositories.play-bundle git git@github.com:endroid/EndroidPlayBundle.git
    sed -i -e 's/;/+ [Endroid\\Bundle\\PlayBundle\\EndroidPlayBundle::class => ["all" => true]];/g' config/bundles.php

    # Use source when installing personal libraries
    sed -i -e s#\"[*]\":#\"endroid/*\":\"source\",\"*\":#g composer.json

    # Application bundles
    composer require \
        doctrine/doctrine-fixtures-bundle \
        friendsofsymfony/user-bundle \
        friendsofsymfony/oauth-server-bundle \
        friendsofsymfony/rest-bundle \
        h4cc/wkhtmltopdf-amd64 \
        hwi/oauth-bundle \
        javiereguiluz/easyadmin-bundle \
        jms/serializer-bundle \
        knplabs/knp-snappy-bundle \
        lexik/jwt-authentication-bundle \
        nelmio/api-doc-bundle \
        php-http/guzzle6-adapter \
        php-http/httplug-bundle \
        sonata-project/doctrine-orm-admin-bundle \
        symfony/swiftmailer-bundle \
        symfony/templating:$SYMFONY_VERSION_MAJOR \
        symfony/web-link:$SYMFONY_VERSION_MAJOR \
        --no-update

    # Personal libraries and bundles
    composer require \
        endroid/calendar:dev-master \
        endroid/cm-sms:dev-master \
        endroid/cm-sms-bundle:dev-master \
        endroid/flusher:dev-master \
        endroid/flusher-bundle:dev-master \
        endroid/guide:dev-master \
        endroid/import:dev-master \
        endroid/play-bundle:dev-master \
        endroid/prediction-io:dev-master \
        endroid/property-access:dev-master \
        endroid/qrcode:dev-master \
        endroid/qrcode-bundle:dev-master \
        endroid/soccer-calendar:dev-master \
        endroid/soccer-data:dev-master \
        endroid/sudoku:dev-master \
        --no-update

        #endroid/data-sanitize:dev-master \
        #endroid/pusher-bundle:dev-master \
        #endroid/soccer-calendar-bundle:dev-master \
        #endroid/tile:dev-master \

    # Development bundles
    composer require \
        symfony/profiler-pack \
        phpmetrics/phpmetrics \
        friendsofphp/php-cs-fixer \
        symfony/phpunit-bridge \
        --no-update --dev

    ../overwrite

    # Update to the latest possible versions
    composer update -n

    ../overwrite

    # Set up frontend
    (
        cd frontend
        ./rebuild
    )
)

# Reset the application itself to make it functional
(
    cd application
    ./reset
)
