#!/usr/bin/env bash

# Always operate from script directory
cd "$(dirname "$0")"

readonly SYMFONY_VERSION=4.0
readonly SHOW_COMMANDS=false

set -e # Break on any error

if [ $SHOW_COMMANDS = true ]; then
    set -o xtrace
fi

if [ ! -f docker/nginx/nginx.conf ]; then
    cp docker/nginx/nginx.conf.dist docker/nginx/nginx.conf
fi

if [ ! -f .env ]; then
    cp .env.dist .env
fi

if [ ! -f overwrites/.env ]; then
    cp overwrites/.env.dist overwrites/.env
fi

# When not in docker start docker and execute script again
if [ ! -d "/var/www/html/docker" ] ; then
    ./stop
    echo y | docker-compose rm
    docker-compose build
    docker-compose up -d
    docker-compose exec nginx docker/nginx/ssl/certbot
    docker-compose exec --user 1000 php /bin/sh rebuild
    exit 0 # Do not continue as we already ran the script above
fi

rm -rf application

readonly SYMFONY_VERSION_MAJOR=^$SYMFONY_VERSION

# Create new project from skeleton and build parts
composer create-project symfony/skeleton:$SYMFONY_VERSION_MAJOR application -s beta

# Further build application
(
    cd application

    composer config minimum-stability beta

    # Symlink directories
    ln -s ../features features
    ln -s ../frontend frontend
    ln -s ../templates templates
    ln -s ../translations translations

    cp config/services.yaml config/services_default.yaml

    (
        cd vendor
        ln -s ../../vendor/endroid endroid
    )

    # Kernel does not work in symlink path so symlink src directories
    (
        cd src
        for directory in `find ../../src/* -maxdepth 0 -type d`
        do
            rm -rf `basename $directory`
            ln -s $directory `basename $directory`
        done
    )

    # Allow auto configuration for user contributed bundles
    composer config extra.symfony.allow-contrib true

    # Add private repositories
    composer config repositories.play-bundle git git@github.com:endroid/EndroidPlayBundle.git
    sed -i -e 's/;/+ [Doctrine\\Bundle\\FixturesBundle\\DoctrineFixturesBundle::class => ["all" => true]];/g' config/bundles.php

    # Use source when installing personal libraries
    sed -i -e s#\"[*]\":#\"endroid/*\":\"source\",\"*\":#g composer.json

    # Application bundles
    composer require \
        doctrine/doctrine-fixtures-bundle \
        easycorp/easyadmin-bundle \
        friendsofsymfony/elastica-bundle \
        friendsofsymfony/oauth-server-bundle:dev-master \
        friendsofsymfony/rest-bundle \
        friendsofsymfony/user-bundle \
        google/apiclient \
        h4cc/wkhtmltopdf-amd64 \
        hwi/oauth-bundle \
        jms/serializer-bundle \
        knplabs/knp-snappy-bundle \
        lexik/jwt-authentication-bundle \
        nelmio/api-doc-bundle \
        php-ai/php-ml \
        php-http/httplug-pack \
        predis/predis \
        pusher/pusher-php-server \
        rpkamp/mailhog-behat-extension \
        rpkamp/mailhog-mink-behat-context \
        sonata-project/doctrine-orm-admin-bundle \
        symfony/lock \
        symfony/swiftmailer-bundle \
        symfony/templating \
        symfony/web-link \
        --no-update

    # Personal libraries and bundles
    composer require \
        endroid/bundle-test:dev-master \
        endroid/calendar:dev-master \
        endroid/cm-sms:dev-master \
        endroid/cm-sms-bundle:dev-master \
        endroid/data-sanitize:dev-master \
        endroid/data-sanitize-bundle:dev-master \
        endroid/flusher:dev-master \
        endroid/flusher-bundle:dev-master \
        endroid/form-bundle:dev-master \
        endroid/guide:dev-master \
        endroid/guide-bundle:dev-master \
        endroid/guidelines:dev-master \
        endroid/image-placeholder:dev-master \
        endroid/import:dev-master \
        endroid/import-bundle:dev-master \
        endroid/import-demo-bundle:dev-master \
        endroid/pdf:dev-master \
        endroid/prediction-io:dev-master \
        endroid/prediction-io-bundle:dev-master \
        endroid/prediction-io-demo-bundle:dev-master \
        endroid/priority-shuffle-random:dev-master \
        endroid/property-access:dev-master \
        endroid/qr-code:dev-master \
        endroid/qr-code-bundle:dev-master \
        endroid/simple-excel:dev-master \
        endroid/soccer-calendar:dev-master \
        endroid/soccer-calendar-bundle:dev-master \
        endroid/soccer-data:dev-master \
        endroid/sudoku:dev-master \
        endroid/sudoku-bundle:dev-master \
        endroid/tile:dev-master \
        endroid/tile-bundle:dev-master \
        endroid/twitter:dev-master \
        --no-update

        # endroid/play-bundle:dev-master \

    # Development bundles
    composer require \
        behat/mink-extension \
        behat/mink-goutte-driver \
        behat/mink-selenium2-driver \
        behat/symfony2-extension \
        friendsofphp/php-cs-fixer \
        phpmetrics/phpmetrics \
        phpstan/phpstan \
        symfony/debug-bundle \
        symfony/profiler-pack \
        symfony/phpunit-bridge \
        --no-update --dev

    ../overwrite

    # Update to the latest possible versions
    composer update -n

    ../overwrite

    chmod +x /var/www/html/application/vendor/php-ai/php-ml/bin/libsvm/*

    rm -rf features/demo.feature

    # Set up frontend
    (
        cd frontend
        ./rebuild
    )
)

# Reset the application itself to make it functional
(
    cd application
    ./reset
)
