#!/usr/bin/env bash

# Always operate from script directory
cd "$(dirname "$0")"

set -e # Break on any error

git reset --hard
OUTPUT=`git pull`

if [ "$OUTPUT"=="Already up-to-date." ]; then
    exit 0
fi

./deploy
