#!/usr/bin/env bash

# Always operate from script directory
cd "$(dirname "$0")"

set -e # Break on any error

git reset --hard
sed -i -e 's/localhost/endroid.nl/g' docker/nginx/nginx.conf
OUTPUT=`git pull`

if [ "$OUTPUT"=="Already up-to-date." ]; then
    exit 0
fi

echo "Changes detected: deploying!"
./deploy
