#nelmio_api_doc:
#    routes:
#        path_patterns:
#            - ^/api/
#    documentation:
#        info:
#            title: API
#            description: Documentation
#            version: 1.0.0
#        securityDefinitions:
#            token:
#                type: apiKey
#                in: header
#                name: Authorization
#                description: Enter value as "Bearer TOKEN"
#        security:
#            - token: []
