services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\ImagePlaceholder\ImagePlaceholder:
        arguments: ['%kernel.debug%', 'placeholderpics', false]
        calls:
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\BaconMockupProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\LoremFlickrProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\LoremPixelProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\PipsumProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\PlaceBearProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\PlaceHoffProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\PlaceholdItProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\PlaceSkullProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\UnsplashItProvider']]
            - [addProvider, ['@Endroid\ImagePlaceholder\Provider\PlaceholderPicsProvider']]

    Endroid\ImagePlaceholder\Twig\Extension\ImagePlaceholderExtension: ~

    Endroid\ImagePlaceholder\Provider\BaconMockupProvider: ~
    Endroid\ImagePlaceholder\Provider\LoremFlickrProvider: ~
    Endroid\ImagePlaceholder\Provider\LoremPixelProvider: ~
    Endroid\ImagePlaceholder\Provider\PipsumProvider: ~
    Endroid\ImagePlaceholder\Provider\PlaceBearProvider: ~
    Endroid\ImagePlaceholder\Provider\PlaceHoffProvider: ~
    Endroid\ImagePlaceholder\Provider\PlaceholdItProvider: ~
    Endroid\ImagePlaceholder\Provider\PlaceSkullProvider: ~
    Endroid\ImagePlaceholder\Provider\UnsplashItProvider: ~
    Endroid\ImagePlaceholder\Provider\PlaceholderPicsProvider: ~
