parameters:
    # Fallback for when variables are not available
    # Avoids errors while warming up cache
    env(TWITTER_CONSUMER_KEY): ''
    env(TWITTER_CONSUMER_SECRET): ''
    env(TWITTER_ACCESS_TOKEN): ''
    env(TWITTER_ACCESS_TOKEN_SECRET): ''

endroid_twitter:
    consumer_key: '%env(TWITTER_CONSUMER_KEY)%'
    consumer_secret: '%env(TWITTER_CONSUMER_SECRET)%'
    access_token: '%env(TWITTER_ACCESS_TOKEN)%'
    access_token_secret: '%env(TWITTER_ACCESS_TOKEN_SECRET)%'
