services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\Pdf\Pdf: ~
    Endroid\Pdf\Factory\AssetFactory: ~
    Endroid\Pdf\Twig\Extension\EmbedExtension: ~
