fos_elastica:
    clients:
        default: { host: elasticsearch, port: 9200 }
    indexes:
        app:
            settings:
                index:
                    number_of_replicas: 0
                    analysis:
                        analyzer:
                            index_analyzer:
                                tokenizer: whitespace
                                filter: [asciifolding, lowercase, ngram]
                            search_analyzer:
                                tokenizer: whitespace
                                filter: [asciifolding, lowercase]
                        filter:
                            ngram:
                                type: ngram
                                min_gram: 3
                                max_gram: 20
                                token_chars: ['letter', 'digit']
            types:
                user:
                    properties:
                        id: ~
                        suggest:
                            type: completion
                            analyzer: index_analyzer
                            search_analyzer: search_analyzer
                    persistence:
                        driver: orm
                        model: App\Entity\User
                        provider: ~
                        listener: ~
                        finder: ~
