knp_snappy:
    pdf:
        enabled: true
        binary: '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:
            - { name: dpi, value: 300 }
            - { name: lowquality, value: false }
            - { name: viewport-size, value: 1024x768 }
            - { name: page-size, value: A4 }
