twig:
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/templates/bundles/FOSUser': FOSUser
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
