#!/usr/bin/env bash

# Always operate from script directory
cd "$(dirname "$0")"

[ "$1" = "public" ] ; PRIVATE=$?

set -e # Break on any error

if [ ! -f docker/nginx/nginx.conf ]; then
    cp docker/nginx/nginx.conf.dist docker/nginx/nginx.conf
fi

if [ ! -f .env ]; then
    cp .env.dist .env
fi

if [ ! -f overwrites/.env ]; then
    cp overwrites/.env.dist overwrites/.env
fi

# When not in docker start docker and execute script again
if [ ! -d "/var/www/html/docker" ] ; then
    ./stop
    echo y | docker-compose rm
    docker-compose build
    docker-compose up -d
    docker-compose exec nginx docker/nginx/ssl/certbot
    docker-compose exec --user 1000 php /bin/sh build
    exit 0 # Do not continue as we already ran the script above
fi

rm -rf application

# Install to latest version of Composer
composer self-update --snapshot

# Create new project from skeleton and build parts
composer create-project symfony/website-skeleton application -s beta --no-install

# Further build application
(
    cd application

    # Application bundles
    composer require \
        google/apiclient \
        php-http/httplug-pack \
        --no-update

    if [ $PRIVATE = 1 ]; then
        composer config repositories.play-bundle vcs git@github.com:endroid/EndroidPlayBundle.git
        composer require endroid/play-bundle:dev-master --no-update
    fi

    # Development bundles
    composer require \
        behat/mink-extension \
        behat/mink-goutte-driver \
        behat/mink-selenium2-driver \
        behat/symfony2-extension \
        behatch/contexts \
        friendsofphp/php-cs-fixer \
        phpmetrics/phpmetrics \
        rpkamp/mailhog-behat-extension \
        rpkamp/mailhog-mink-behat-context \
        --no-update --dev

    cp -a ../overwrites/. .

    if [ $PRIVATE = 0 ]; then
        rm -rf config/routes/endroid_play.yaml
    fi

    # Update to the latest possible versions
    COMPOSER_MEMORY_LIMIT=-1 composer update -n

    # Allow fixtures in production environment
    sed -i -e 's/Doctrine\\Bundle\\FixturesBundle\\DoctrineFixturesBundle::class => \[\x27dev\x27 => true, \x27test\x27 => true\],/Doctrine\\Bundle\\FixturesBundle\\DoctrineFixturesBundle::class => \[\x27all\x27 => true\],/g' config/bundles.php

    chmod +x /var/www/html/application/vendor/php-ai/php-ml/bin/libsvm/*

    rm -rf features/demo.feature

    # Set up assets
    (
        cd assets
        ./build
    )
)

# Reset the application itself to make it functional
(
    cd application
    bin/reset
)
