#!/usr/bin/env bash

# Always operate from script directory
cd "$(dirname "$0")"

[ "$1" = "public" ] ; PRIVATE=$?

set -e # Break on any error

if [ ! -f docker/nginx/nginx.conf ]; then
    cp docker/nginx/nginx.conf.dist docker/nginx/nginx.conf
fi

if [ ! -f .env ]; then
    cp .env.dist .env
fi

if [ ! -f overwrites/.env ]; then
    cp overwrites/.env.dist overwrites/.env
fi

# When not in docker start docker and execute script again
if [ ! -d "/var/www/html/docker" ] ; then
    ./stop
    echo y | docker-compose rm
    docker-compose build
    docker-compose up -d
    docker-compose exec nginx docker/nginx/ssl/certbot
    docker-compose exec --user 1000 php /bin/sh build
    exit 0 # Do not continue as we already ran the script above
fi

rm -rf application

# Install to latest version of Composer
composer self-update --snapshot

# Create new project from skeleton and build parts
composer create-project symfony/website-skeleton application -s beta --no-install

# Further build application
(
    cd application

    # Allow auto configuration for user contributed bundles
    composer config extra.symfony.allow-contrib true

    # Also install beta packages
    composer config minimum-stability beta

    # Allow SF new structure detection
    mkdir config config/packages public src

    # Symlink directories
    ln -s ../assets assets
    ln -s ../features features
    ln -s ../templates templates
    ln -s ../translations translations

    mkdir vendor
    (
        cd vendor
        ln -s ../../vendor/endroid endroid
    )

    # Kernel does not work in symlink path so symlink src directories
    (
        cd src
        for directory in `find ../../src/* -maxdepth 0 -type d`
        do
            rm -rf `basename $directory`
            ln -s $directory `basename $directory`
        done
    )

    # Use source when installing personal libraries
    sed -i -e s#\"[*]\":#\"endroid/*\":\"source\",\"*\":#g composer.json

    # Application bundles
    composer require \
        api-platform/api-pack \
        doctrine/doctrine-migrations-bundle \
        doctrine/doctrine-fixtures-bundle \
        easycorp/easyadmin-bundle \
        friendsofsymfony/ckeditor-bundle \
        friendsofsymfony/elastica-bundle \
        friendsofsymfony/user-bundle \
        google/apiclient \
        hwi/oauth-bundle \
        knplabs/knp-snappy-bundle \
        lexik/jwt-authentication-bundle \
        php-ai/php-ml \
        php-http/httplug-pack \
        predis/predis \
        pusher/pusher-php-server \
        sonata-project/doctrine-orm-admin-bundle \
        symfony/lock \
        symfony/messenger \
        webonyx/graphql-php \
        endroid/asset:dev-master \
        endroid/calendar:dev-master \
        endroid/cm-sms:dev-master \
        endroid/cm-sms-bundle:dev-master \
        endroid/data-sanitize:dev-master \
        endroid/data-sanitize-bundle:dev-master \
        endroid/data-sanitize-demo-bundle:dev-master \
        endroid/embed:dev-master \
        endroid/flusher:dev-master \
        endroid/flusher-bundle:dev-master \
        endroid/form-bundle:dev-master \
        endroid/guide:dev-master \
        endroid/guide-bundle:dev-master \
        endroid/guidelines:dev-master \
        endroid/image-placeholder:dev-master \
        endroid/import:dev-master \
        endroid/import-bundle:dev-master \
        endroid/import-demo-bundle:dev-master \
        endroid/installer:dev-master \
        endroid/pdf:dev-master \
        endroid/priority-shuffle-random:dev-master \
        endroid/property-access:dev-master \
        endroid/qr-code:dev-master \
        endroid/qr-code-bundle:dev-master \
        endroid/simple-excel:dev-master \
        endroid/soccer-calendar:dev-master \
        endroid/soccer-calendar-bundle:dev-master \
        endroid/soccer-data:dev-master \
        endroid/sudoku:dev-master \
        endroid/sudoku-bundle:dev-master \
        endroid/teleporter:dev-master \
        endroid/tile:dev-master \
        endroid/tile-bundle:dev-master \
        endroid/twitter:dev-master \
        --no-update

    if [ $PRIVATE = 1 ]; then
        composer config repositories.play-bundle vcs git@github.com:endroid/EndroidPlayBundle.git
        composer require endroid/play-bundle:dev-master --no-update
    fi

    # Development bundles
    composer require \
        behat/mink-extension \
        behat/mink-goutte-driver \
        behat/mink-selenium2-driver \
        behat/symfony2-extension \
        behatch/contexts \
        friendsofphp/php-cs-fixer \
        phpmetrics/phpmetrics \
        rpkamp/mailhog-behat-extension \
        rpkamp/mailhog-mink-behat-context \
        --no-update --dev

    cp -a ../overwrites/. .

    if [ $PRIVATE = 0 ]; then
        rm -rf config/routes/endroid_play.yaml
    fi

    # Update to the latest possible versions
    COMPOSER_MEMORY_LIMIT=-1 composer update -n

    # Allow fixtures in production environment
    sed -i -e 's/Doctrine\\Bundle\\FixturesBundle\\DoctrineFixturesBundle::class => \[\x27dev\x27 => true, \x27test\x27 => true\],/Doctrine\\Bundle\\FixturesBundle\\DoctrineFixturesBundle::class => \[\x27all\x27 => true\],/g' config/bundles.php

    chmod +x /var/www/html/application/vendor/php-ai/php-ml/bin/libsvm/*

    rm -rf features/demo.feature

    # Set up assets
    (
        cd assets
        ./build
    )
)

# Reset the application itself to make it functional
(
    cd application
    bin/reset
)
