# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # disable the sending of email altogether
    disable_delivery: false
    # ... or send all email to a specific address
    #delivery_addresses: ['me@example.com']
