parameters:
    mailer_user: info@endroid.nl

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Aliases
    FOS\OAuthServerBundle\Entity\ClientManager: '@fos_oauth_server.client_manager.default'
    FOS\UserBundle\Model\UserManagerInterface: '@fos_user.user_manager.default'

    # Custom services
    App\Security\UserProvider:
        $properties: {}

    admin.model_manager:
        class: App\Admin\ModelManager
        arguments: ['@doctrine']

    admin.service:
        class: App\Admin\ServiceAdmin
        arguments: [~, App\Entity\Knife\Service, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Service, group: Content }
        calls:
            - [ addChild, [ '@admin.field' ] ]
            - [ addChild, [ '@admin.product' ] ]
        public: true

    admin.field:
        class: App\Admin\FieldAdmin
        arguments: [~, App\Entity\Knife\AbstractField, ~]
        calls:
            - [ setSubClasses, [{check: App\Entity\Knife\CheckField, text: App\Entity\Knife\TextField}]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Field, show_in_dashboard: false }
        public: true

    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Knife\Product, ~]
        tags:
            - { name: sonata.admin, model_manager: admin.model_manager, manager_type: orm, label: Product, show_in_dashboard: false }
        public: true
