imports:
    - { resource: services_no_autowire.yaml }
    - { resource: services_default.yaml }

parameters:
    locale: 'en'
    mailer_user: 'info@endroid.nl'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Aliases
    FOS\OAuthServerBundle\Entity\ClientManager: '@fos_oauth_server.client_manager.default'
    FOS\UserBundle\Model\UserManagerInterface: '@fos_user.user_manager.default'

    App\Controller\Search\SuggestController:
        public: true
        arguments:
            $searchable: '@fos_elastica.index.app.user'

    # Custom services
    App\Security\UserProvider:
        $properties: { google: googleId, github: githubId }

    admin.model_manager:
        class: App\Admin\ModelManager
        arguments: ['@doctrine']

    fos_oauth_server.storage.default:
        class: App\Security\OAuth\TokenStorage
        arguments:
            - '@fos_oauth_server.client_manager'
            - '@fos_oauth_server.access_token_manager'
            - '@fos_oauth_server.refresh_token_manager'
            - '@fos_oauth_server.auth_code_manager'
            - '@fos_user.user_provider.username'
            - '@security.encoder_factory'
