hwi_oauth:
    firewall_names: [main]
    resource_owners:
        google:
            type: google
            client_id: '%google_oauth_client_id%'
            client_secret: '%google_oauth_client_secret%'
            scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
    fosub:
        username_iterations: 30
        properties:
            google: googleId
