api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
