services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.filter.locale:
        class: AppBundle\Filter\LocaleFilter
        arguments: [ '@doctrine.orm.entity_manager' ]
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    app.block.service.stats:
        class: AppBundle\Block\Service\StatsBlockService
        arguments: [ 'app.block.service.stats', '@templating' ]
        tags:
            - { name: sonata.block }
