#!/usr/bin/env bash

set -e # Break on any error

#security-checker security:check
#vendor/bin/behat
vendor/bin/phpunit
frontend/node_modules/.bin/psi endroid.nl --threshold=75
php-cs-fixer fix src --rules=@Symfony
php-cs-fixer fix vendor/endroid --rules=@Symfony
