#!/usr/bin/env bash

# Always operate from script directory
cd "$(dirname "$0")"

set -e # Break on any error

cp .env.test .env

vendor/bin/behat --stop-on-failure
vendor/bin/simple-phpunit

cp ../overwrites/.env .env
