# Translations of prefixes for multilingual routes can be defined in
# src/AppBundle/Resources/translations/routes.<lang>.yml

api:
    resource: "@ApiBundle/Resources/config/routes.yml"
    type: rest
    prefix: /api
    options: { i18n: false }

dashboard:
    resource: "@EndroidDashboardBundle/Controller/"
    type: annotation
    prefix: /dashboard



elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api-doc

#intake:
#    resource: "@EndroidIntakeBundle/Controller/"
#    type: annotation
#    prefix: /intakes

#lexik_translation_edition:
#    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
#    prefix: /admin/translations

news:
    resource: "@NewsBundle/Controller/"
    type: annotation
    prefix: /news

page:
    resource: "@PageBundle/Controller/"
    type: annotation
    prefix: /pages

pdf:
    resource: "@PdfBundle/Controller/"
    type: annotation
    prefix: /pdf

play:
    resource: "@EndroidPlayBundle/Controller/"
    type: annotation





search:
    resource: "@SearchBundle/Controller/"
    type: annotation
    prefix: /search


sitemap:
    resource: "@SitemapBundle/Controller/"
    type: annotation

sudoku:
    resource: "@EndroidSudokuBundle/Controller/"
    type: annotation
    prefix: sudoku

task:
    resource: "@TaskBundle/Controller/"
    type: annotation
    prefix: /tasks

tile:
    resource: "@EndroidTileBundle/Controller/"
    type: annotation
    prefix: /tile

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /easy-admin

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /oauth-connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /oauth-login

google_login:
    path: /oauth-login/check-google

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: AppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]