stages:
  - behat
  - phpunit
#  - wdio-e2e

image: dockerphp/gitlab-ci-pipeline:7.2-alpine

services:
  - mariadb

cache:
  paths:
    - vendor/

before_script:
  - cp .env.gitlab .env
  - bin/setup test

variables:
  MYSQL_ROOT_PASSWORD: root

behat:
  stage: behat
  artifacts:
    name: "Failure report"
    paths:
      - tests/report/
      - var/log/test.log
    when: on_failure
    expire_in: 1 week
  script:
    - bin/test-behat

phpunit:
  stage: phpunit
  script:
    - bin/test-phpunit

#wdio-e2e:
#  stage: wdio-e2e
#  artifacts:
#    name: "Failure report"
#    paths:
#      - tests/report/
#      - var/log/test.log
#    when: on_failure
#    expire_in: 1 week
#  script:
#    - bin/setup-wdio-e2e-gitlab
#    - bin/test-wdio-e2e gitlab
