easy_admin:
    site_name: Application
    design:
        color_scheme: 'dark'
    entities:
        User:
            label: Users
            class: UserBundle\Entity\User
            list:
                fields:
                    - { property: 'username', label: 'Username'}
                    - { property: 'enabled', label: 'Enabled' }
                    - { property: 'locale', label: 'Locale' }