endroid_twitter:
    consumer_key: 5GkVAUMHPcZRmEDsFVf7aw
    consumer_secret: iY5XOHSqYPjzWscyA5n2EW2SN36iX7oblRqdF4azIQE
    access_token: 23750614-H4yWiPYE3ykpdPhxxu3cYGjsHV5Bdd4QYJXGx5omY
    access_token_secret: RBzkh9MpKZhMhakDuxxsQNxWP5IK1wCArJv1Pv5qV7c
