fos_user:
    db_driver: orm # or mongodb
    firewall_name: main
    user_class: UserBundle\Entity\User
    group:
        group_class: UserBundle\Entity\Group
    from_email:
        address: noreply@example.com
        sender_name: Symfony Application

services:
    fos_user.doctrine_registry:
        alias: doctrine

user:
    whitelist: '%user_whitelist%'