knp_snappy:
    pdf:
        enabled: true
        binary: '%kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:
            - { name: dpi, value: 150 }
            - { name: lowquality, value: false }
            - { name: disable-smart-shrinking, value: true }
            - { name: margin-top, value: 0 }
            - { name: margin-right, value: 0 }
            - { name: margin-bottom, value: 0 }
            - { name: margin-left, value: 0 }
            - { name: viewport-size, value: 1024x768 }
            - { name: page-size, value: A4 }