sonata_admin:
    title: Application
    title_logo: /bundles/admin/img/logo-title.png
    templates:
        layout: AdminBundle::layout.html.twig
#        search_result_block:  'AppBundle:Admin/Block:block_search_result.html.twig'
    options:
        html5_validate: false
    security:
        handler: sonata.admin.security.handler.role
    extensions:
        endroid_behavior.admin.extension.publishable:
            implements:
                - Endroid\Bundle\BehaviorBundle\Model\PublishableInterface
        endroid_behavior.admin.extension.sortable:
            implements:
                - Endroid\Bundle\BehaviorBundle\Model\SortableInterface
        endroid_behavior.admin.extension.traversable:
            implements:
                - Endroid\Bundle\BehaviorBundle\Model\TraversableInterface
        wsse.admin.extension.user:
            implements:
                - WsseBundle\Model\WsseUserInterface
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: app.block.service.stats
            -
                class: col-lg-3 col-xs-6
                position: top
                type: sonata.admin.block.stats
                settings:
                    code: news.admin.article_admin
                    icon:  ion-edit
                    text:  Articles
                    template: AdminBundle:Block:block_stats.html.twig
                    color: bg-green
                    filters:
                        edited: { value: 1 }
            -
                class: col-lg-3 col-xs-6
                position: top
                type: sonata.admin.block.stats
                settings:
                    code: page.admin.page_admin
                    icon: ion-pricetags
                    text: Pages
                    template: AdminBundle:Block:block_stats.html.twig
                    color: bg-green
                    filters:
                        edited: { value: 1 }
            -
                class: col-lg-3 col-xs-6
                position: top
                type: sonata.admin.block.stats
                settings:
                    code: user.admin.user_admin
                    icon: ion-person
                    text: Users
                    template: AdminBundle:Block:block_stats.html.twig
                    color: bg-yellow
                    filters:
                        edited: { value: 1 }
            -
                class: col-lg-3 col-xs-6
                position: top
                type: sonata.admin.block.stats
                settings:
                    code: user.admin.group_admin
                    icon: ion-ios-people
                    text: User groups
                    template: AdminBundle:Block:block_stats.html.twig
                    color: bg-yellow
                    filters:
                        edited: { value: 1 }