easy_admin:
    site_name: Symfony Application
    design:
        brand_color: '#222f5b'
    entities:
        User:
            label: Users
            class: App\Entity\User
            list:
                fields:
                    - { property: 'id', label: 'ID'}
                    - { property: 'email', label: 'Email'}
