services:
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin.menu.user, label: admin.user.label, label_catalogue: admin, show_in_dashboard: true }
