services:
    pdf.route_provider:
        class: PdfBundle\Service\RouteProvider
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            -  { name: route.provider }
